AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance             #1
    #DeletionPolicy: Retain       #Stack deletion don't delete the EC2
    Properties:
      InstanceType: t2.micro
      ImageId: ami-058fea0dcd5b42f9c # Amazon Linux AMI in N.Virginia
      KeyName: newkipi
      Tags:
        - Key: Name
          Value: proje1
      UserData:
        Fn::Base64:                                # YAML makes userdata much cleaner
        #  !Sub |
              #!/bin/bash -ex
              yum install -y httpd;
              echo "<html>I love YAML CloudFormation!!</html>" > /var/www/html/index.html;
              cd /var/www/html;
              chmod 755 index.html;
              service httpd start;
              chkconfig httpd on;

  S3bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: proje1
