AWSTemplateFormatVersion: '2010-09-09'

Resources:
  TaskRole:
      Type: AWS::IAM::Role
      Properties:
          RoleName: !Sub ${AWS::StackName}-task-role
          Path: /
          AssumeRolePolicyDocument:
              Version: 2012-10-17
              Statement:
                  - Effect: Allow
                    Principal:
                        Service:
                            - ecs-tasks.amazonaws.com
                    Action: sts:AssumeRole
          Policies:
              - PolicyName: !Sub ecs-${AWS::StackName}
                PolicyDocument:
                    Version: "2012-10-17"
                    Statement:
                        - Action:
                              - "ecs:RegisterTaskDefinition"
                              - "ecs:ListClusters"
                              - "ecs:DescribeContainerInstances"
                              - "ecs:ListTaskDefinitions"
                              - "ecs:DescribeTaskDefinition"
                              - "ecs:DeregisterTaskDefinition"
                          Effect: Allow
                          Resource: "*"
                        - Action:
                              - "ecs:ListContainerInstances"
                              - "ecs:DescribeClusters"
                          Effect: Allow
                          Resource:
                              - !Sub "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:cluster/myClus"
                        - Action:
                              - "ecs:RunTask"
                          Effect: Allow
                          Condition:
                              ArnEquals:
                                  ecs:cluster:
                                      - !Sub "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:cluster/myClus"
                          Resource: !Sub "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:task-definition/*"
                        - Action:
                              - "ecs:StopTask"
                          Effect: Allow
                          Condition:
                              ArnEquals:
                                  ecs:cluster:
                                      -  "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:cluster/myClus"
                          Resource: "arn:aws:ecs:*:*:task/*" # "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:task/*"
                        - Action:
                              - "ecs:DescribeTasks"
                          Effect: Allow
                          Condition:
                              ArnEquals:
                                  ecs:cluster:
                                      - "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:cluster/myClus"
                          Resource:  "arn:aws:ecs:*:*:task/*" # "arn:aws:ecs:${AWS::Region}:${AWS::AccountId}:task/*"
