name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        uses: actions/checkout@v2
        
      - name: Build the image
        uses: docker/build-push-action@v1 # Info: https://github.com/docker/build-push-action/tree/releases/v1#tags
        run: docker build . --file Dockerfile --tag githubaction:test
