name: Backend Chat CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: node

  cd:
    runs-on: self-hosted
    needs: ci

    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: docker build -t back .
      - name: Tags
        run: |
          docker tag back ${{ secrets.DOCKER_USER }}/back:${{ github.sha }}
          docker tag back ${{ secrets.DOCKER_USER }}/back:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/back:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/back:latest
